name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install all
      run: |
        python -m pip install --upgrade pip
        export INSTALL_DIR="~/dev/sharadar_db_bundle"
        mkdir -p $INSTALL_DIR
        cd $INSTALL_DIR
        python -m pip install --upgrade pip
        pip install pytest
        cd /usr/local/lib/python3.6/site-packages

        # Install TA LIB
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar xvfz ta-lib-0.4.0-src.tar.gz
        rm ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure
        make
        cd ..

        # Install zipline-trades and deps
        git clone https://github.com/shlomikushchi/zipline-trader.git
        cd zipline-trader
        pip install wheel
        pip install -r etc/requirements_build.in
        export DISABLE_BCOLZ_AVX2=true
        pip install --no-binary=bcolz -e .[all] -r etc/requirements_blaze.in
        cd ..

        # Install TWS api
        wget https://interactivebrokers.github.io/downloads/twsapi_macunix.976.01.zip
        unzip twsapi_macunix.976.01.zip -d twsapi
        cd twsapi/IBJts/source/pythonclient
        python setup.py install
        cd -

        pip install memoization singleton_decorator quandl pyfolio
        pip install pandas==0.22.0
        git clone https://github.com/alphaville76/sharadar_db_bundle.git
        cd sharadar_db_bundle
        python setup.py install
        python test/basic_pipeline_sep_db.py


